"""empty message

Revision ID: 001c2266293c
Revises: 4386fd4a7afa
Create Date: 2023-05-31 11:32:15.037811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001c2266293c'
down_revision = '4386fd4a7afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_name', sa.String(length=160), nullable=False),
    sa.Column('course_desc', sa.String(length=600), nullable=True),
    sa.Column('course_price', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=True),
    sa.Column('secure_url', sa.String(length=160), nullable=True),
    sa.Column('public_id', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    # ### end Alembic commands ###
