"""empty message

Revision ID: 12a0ba7144cc
Revises: da8e09e37f80
Create Date: 2023-06-03 14:21:27.296516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a0ba7144cc'
down_revision = 'da8e09e37f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_course',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], )
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=180),
               type_=sa.String(length=280),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=280),
               type_=sa.VARCHAR(length=180),
               existing_nullable=False)

    op.drop_table('student_course')
    # ### end Alembic commands ###
