"""empty message

Revision ID: 483bf6651105
Revises: 001c2266293c
Create Date: 2023-05-31 14:50:15.635502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483bf6651105'
down_revision = '001c2266293c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('course_price',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('course_price',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
