"""empty message

Revision ID: 63b5f372c9f2
Revises: fa15010d5de9
Create Date: 2022-10-05 22:14:30.309729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b5f372c9f2'
down_revision = 'fa15010d5de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('public_id', sa.String(length=100), nullable=False))
    op.add_column('images', sa.Column('secure_url', sa.String(length=140), nullable=False))
    op.alter_column('images', 'filename_image',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.drop_column('images', 'path_image')
    op.drop_column('images', 'relative_path_image')
    op.add_column('videos', sa.Column('public_id', sa.String(length=100), nullable=False))
    op.add_column('videos', sa.Column('secure_url', sa.String(length=140), nullable=False))
    op.drop_column('videos', 'path_video')
    op.drop_column('videos', 'relative_path_video')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('relative_path_video', sa.VARCHAR(length=140), autoincrement=False, nullable=False))
    op.add_column('videos', sa.Column('path_video', sa.VARCHAR(length=140), autoincrement=False, nullable=False))
    op.drop_column('videos', 'secure_url')
    op.drop_column('videos', 'public_id')
    op.add_column('images', sa.Column('relative_path_image', sa.VARCHAR(length=140), autoincrement=False, nullable=False))
    op.add_column('images', sa.Column('path_image', sa.VARCHAR(length=140), autoincrement=False, nullable=False))
    op.alter_column('images', 'filename_image',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('images', 'secure_url')
    op.drop_column('images', 'public_id')
    # ### end Alembic commands ###
