"""empty message

Revision ID: 65078e5d4230
Revises: 599a5de00802
Create Date: 2022-12-14 20:44:18.488093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65078e5d4230'
down_revision = '599a5de00802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('uri', sa.String(length=200), nullable=False))
    op.drop_column('videos', 'public_id')
    op.drop_column('videos', 'secure_url')
    op.drop_column('videos', 'filename_video')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('filename_video', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('videos', sa.Column('secure_url', sa.VARCHAR(length=140), autoincrement=False, nullable=False))
    op.add_column('videos', sa.Column('public_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('videos', 'uri')
    # ### end Alembic commands ###
