"""empty message

Revision ID: 76676a469a87
Revises: 958aa59e553b
Create Date: 2023-06-04 18:08:17.149941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76676a469a87'
down_revision = '958aa59e553b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
