"""Created conten_page table

Revision ID: 7a0d410fc1d6
Revises: 17ce27acec23
Create Date: 2022-07-19 18:14:39.698964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0d410fc1d6'
down_revision = '17ce27acec23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('information_content', sa.String(length=1500), nullable=False),
    sa.Column('from_page', sa.String(length=50), nullable=False),
    sa.Column('from_section', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_page')
    # ### end Alembic commands ###
