"""Updating videos table

Revision ID: 7dbd8b243acb
Revises: 7e060f6f02d3
Create Date: 2022-07-02 21:22:18.499950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dbd8b243acb'
down_revision = '7e060f6f02d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('description', sa.String(length=200), nullable=True))
    op.add_column('videos', sa.Column('public_id', sa.String(length=140), nullable=False))
    op.add_column('videos', sa.Column('path_video', sa.String(length=140), nullable=False))
    op.add_column('videos', sa.Column('filename_video', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'filename_video')
    op.drop_column('videos', 'path_video')
    op.drop_column('videos', 'public_id')
    op.drop_column('videos', 'description')
    # ### end Alembic commands ###
