"""Updated admin user table

Revision ID: 7e060f6f02d3
Revises: f45e70dbad86
Create Date: 2022-06-19 12:26:49.799129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e060f6f02d3'
down_revision = 'f45e70dbad86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('firstname', sa.String(length=25), nullable=False))
    op.add_column('admin', sa.Column('lastname', sa.String(length=25), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'lastname')
    op.drop_column('admin', 'firstname')
    # ### end Alembic commands ###
