"""empty message

Revision ID: 958aa59e553b
Revises: 12a0ba7144cc
Create Date: 2023-06-04 11:16:49.553506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958aa59e553b'
down_revision = '12a0ba7144cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_paypal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchase_paypal_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchase_net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_paypal')
    # ### end Alembic commands ###
