"""empty message

Revision ID: a2b3a2cd207e
Revises: f568627a6b24
Create Date: 2023-06-15 18:33:56.075337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b3a2cd207e'
down_revision = 'f568627a6b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=600), nullable=False),
    sa.Column('answer', sa.String(length=900), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faq'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faq')
    # ### end Alembic commands ###
