"""empty message

Revision ID: c81a3cda8332
Revises: 53f5a47026f6
Create Date: 2023-06-09 16:59:09.578303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81a3cda8332'
down_revision = '53f5a47026f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_name', sa.String(length=160), nullable=False),
    sa.Column('cycle_desc', sa.String(length=600), nullable=True),
    sa.Column('cycle_code', sa.String(length=20), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cycle')
    # ### end Alembic commands ###
