"""Created images table

Revision ID: cee4a8773045
Revises: 7a0d410fc1d6
Create Date: 2022-07-27 16:11:34.015983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee4a8773045'
down_revision = '7a0d410fc1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_image', sa.String(length=140), nullable=False),
    sa.Column('filename_image', sa.String(length=120), nullable=False),
    sa.Column('from_page', sa.String(length=50), nullable=False),
    sa.Column('from_section', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
