"""Adding payment_completed to users column

Revision ID: da0985cfec3a
Revises: c23b6a1e1635
Create Date: 2022-05-05 16:51:21.035020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0985cfec3a'
down_revision = 'c23b6a1e1635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('payment_completed', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'payment_completed')
    # ### end Alembic commands ###
