"""empty message

Revision ID: da8e09e37f80
Revises: 483bf6651105
Create Date: 2023-05-31 23:39:20.263136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8e09e37f80'
down_revision = '483bf6651105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change')
    # ### end Alembic commands ###
