"""empty message

Revision ID: e1bcc31819b5
Revises: aad84d708840
Create Date: 2023-06-11 17:13:57.963718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1bcc31819b5'
down_revision = 'aad84d708840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_name', sa.String(length=160), nullable=False),
    sa.Column('material_url', sa.String(length=300), nullable=True),
    sa.Column('material_code', sa.String(length=20), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name=op.f('fk_material_video_id_video'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material')
    # ### end Alembic commands ###
