"""Creating admin table

Revision ID: f45e70dbad86
Revises: da0985cfec3a
Create Date: 2022-05-08 18:20:09.992131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45e70dbad86'
down_revision = 'da0985cfec3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=160), nullable=False),
    sa.Column('email_adress', sa.String(length=160), nullable=False),
    sa.Column('gravatar', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_adress'),
    sa.UniqueConstraint('gravatar'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
