"""empty message

Revision ID: f568627a6b24
Revises: e1bcc31819b5
Create Date: 2023-06-11 18:32:21.622388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f568627a6b24'
down_revision = 'e1bcc31819b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_path', sa.String(length=300), nullable=True))
        batch_op.drop_column('material_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_url', sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('material_path')

    # ### end Alembic commands ###
