"""Change video table rows

Revision ID: fa15010d5de9
Revises: d7222d86caf7
Create Date: 2022-09-21 22:16:05.896690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa15010d5de9'
down_revision = 'd7222d86caf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('relative_path_video', sa.String(length=140), nullable=False))
    op.drop_constraint('videos_url_video_key', 'videos', type_='unique')
    op.drop_column('videos', 'public_id')
    op.drop_column('videos', 'url_video')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('url_video', sa.VARCHAR(length=180), autoincrement=False, nullable=False))
    op.add_column('videos', sa.Column('public_id', sa.VARCHAR(length=140), autoincrement=False, nullable=False))
    op.create_unique_constraint('videos_url_video_key', 'videos', ['url_video'])
    op.drop_column('videos', 'relative_path_video')
    # ### end Alembic commands ###
